default: &default
  adapter: postgresql
  encoding: unicode
  # For Rails 6 and later, pool and timeout are highly recommended
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: music_app_development

test:
  <<: *default
  database: music_app_test

production:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  database: music_app_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: 5432